# Make vi the default editor
export EDITOR="vi"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
# Make some commands not show up in history
# not sure about this one... might be useful in the future
# export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Prefer US English and use UTF-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Highlight section titles in manual pages
export LESS_TERMCAP_md="$ORANGE"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# set symbol per env
shell_is_linux && export PROMPT_SYMBOL="\[\033[0;36m\]☯\[\033[0m\]"
shell_is_osx && export PROMPT_SYMBOL="\[\033[1;32m\]λ\[\033[0m\]"
# purple star
# export PROMPT_SYMBOL="\[\033[0;35m\]★\[\033[0m\]"